### ISSUE TITLE
App unexpectedly exits when a picture or file is copied to the clipboard on Windows

### ISSUE THREAD

**Issue by ChloeWKY** [Alex222222222222/CopyClip#115]
The latest version is used.

The app also exits unexpectedly when Youdao Dictionary's word marking feature is used. This seems to be unrelated to file copying and rather associated with text data handling.

**Comment by ChloeWKY** [comment]
The latest version is used.

**Comment by Alex222222222222** [comment]
Please upload or pasta your associated log file here, otherwise there is no way I can diagnose the issue.

The log file is located at `%appdata%/org.eu.huazifan.copyclip/log` or `% localappdata%/org.eu.huazifan.copyclip/log` on Windows.

**Comment by ChloeWKY** [comment]
> Please upload or pasta your associated log file here, otherwise there is no way I can diagnose the issue.
> 
> The log file is located at `%appdata%/org.eu.huazifan.copyclip/log` or `% localappdata%/org.eu.huazifan.copyclip/log` on Windows.

@Alex222222222222 
Email sent. Please check your mailbox for the attached files.

**Comment by ChloeWKY** [comment]
TODO: 补充
在有道词典使用划词功能时，APP也会闪退。

**Comment by Alex222222222222** [comment]
Please do not closed this issue, as the bug fix has not been merged yet.

**Comment by ChloeWKY** [comment]
Resolved.

**Comment by Alex222222222222** [comment]
Please do not closed this issue, as the bug fix has not been merged yet, and the bug fix is not sophisticated tested.

**Comment by ChloeWKY** [comment]
Sure. It's your business now.

**Comment by ChloeWKY** [comment]
No, the bug was not fixed by your latest change. GitHub build failed/cancelled on this commit, and after installing new package file from release, the "updated" app still have the same issue as before.

**Comment by Alex222222222222** [comment]
The GitHub build was failed due to a latest issue with tauri-cli. There is currently no fix other than downgrade the tauri-cli version, or wait for the fix by tauri team.

You could build the latest version on your own computer with a lower tauri-cli version. That should fix the issue.
